
trigger:
- master

pr: none

name: 1.0.$(BuildID)

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'runtime'
    version: '7.x'
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '6.5.0'
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'
    vstsFeed: '087f7b3b-2160-4d35-8fb9-36edb3d5651b'
- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '**/*.csproj'
    versioningScheme: 'byBuildNumber'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'